version: '3'
services:
  python:
    container_name: python_container
    build:
      context: ./
      dockerfile: Dockerfile
    volumes:
      - ./project:/work:cached
    ports:
      - "8000:8000"
      - "8080:8080"
    command: /bin/sh -c "while sleep 1000; do :; done"
 
